version: "3.5"

services:
  app:
    build:
      context: .
      args:
        NEW_UID: ${NEW_UID:-1000}
        NEW_GID: ${NEW_GID:-1000}
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/src
      - ./secrets:/src/secrets
    ports:
      - 6502:6502
    depends_on:
      - softhsm
      - redis
    networks:
      zmodules:
        aliases:
          - prs-app

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - zmodules

  softhsm:
    image: cremuzzi/softhsm2
    volumes:
      - ./softhsm.conf:/etc/softhsm2/softhsm2.conf
      - ./tokens:/var/lib/softhsm/tokens
    networks:
      - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules

volumes:
  secrets:
    name: secrets