version: "3.5"

services:
  app:
    build:
      context: .
      args:
        NEW_UID: ${NEW_UID:-1000}
        NEW_GID: ${NEW_GID:-1000}
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/src
      - ./secrets:/usr/local/secrets
    ports:
      - 6502:6502
    depends_on:
      - redis
    networks:
      zmodules:
        aliases:
          - prs-app

  app-ssl:
    image: httpd
    restart: no
    ports:
      - 6503:443
    volumes:
      - ./secrets:/usr/local/secrets
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
    depends_on:
      - app
    networks:
      zmodules:
          aliases:
          - prs-app-ssl

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules

volumes:
  secrets:
    name: secrets
