services:
  app:
    build:
      context: .
      args:
        NEW_UID: ${NEW_UID:-1000}
        NEW_GID: ${NEW_GID:-1000}
      dockerfile: docker/Dockerfile
    environment:
        FASTAPI_CONFIG_PATH: /src/app.conf
    volumes:
      - ./:/src
      - ./secrets:/usr/local/secrets
    ports:
      - 6502:6502
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  app-ssl:
    profiles: [ssl]
    image: httpd
    restart: no
    ports:
      - 6503:443
    volumes:
      - ./secrets:/usr/local/secrets
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
    depends_on:
      - app

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --user postgres"]
      start_period: 30s
      start_interval: 1s
    ports:
      - 5432:5432
    volumes:
      - './docker/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'

volumes:
  secrets:
    name: secrets
  pgdata:
    name: pgdata
