[tool.poetry]
name = "gfmodules-prs"
version = "0.1.0"
description = ""
license = "EUPL-1.2"
authors = ["Ministerie van Volksgezondheid, Welzijn en Sport"]
repository = "https://github.com/minvws/gfmodules-prs-private"
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.34.3"
fastapi = "^0.115"
async-timeout = "5.0.1"
mypy = "^1.16.0"
pydantic-settings = "^2.9.1"
inject = "^5.2.0"
pycryptodome = "^3.23.0"
pydantic = "^2.11.5"
redis = "^5.0.8"
cryptography = "^45.0.3"
cffi = "^1.17.1"
pykcs11 = "^1.5.16"
filelock = "^3.18.0"
asn1crypto = "^1.5.1"
validators = "^0.35.0"
requests = "^2.32.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
pytest-cov = "^6.1.1"
pytest-mock = "^3.14.1"
httpx = "^0.28.1"
ruff = "^0.11.13"
safety = "^3.2.3"
codespell = "^2.2.6"
types-requests = "^2.32.0.20250602"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
cache-dir = "~/.cache/ruff"
include = [
    "pyproject.toml",
    "app/*.py",
    "tests/*.py",
]

[tool.mypy]
files = "app,tests"
python_version = "3.11"
strict = true
cache_dir = "~/.cache/mypy"
ignore_missing_imports = true

[tool.pytest.ini_options]
cache_dir = "~/.cache/pytest"
testpaths = [
    "tests",
]
