[tool.poetry]
name = "gfmodules-prs"
version = "0.1.0"
description = ""
license = "EUPL-1.2"
authors = ["Ministerie van Volksgezondheid, Welzijn en Sport"]
repository = "https://github.com/minvws/gfmodules-prs-private"
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.26.0"
fastapi = "^0.109.1"
async-timeout = "4.0.3"
mypy = "^1.8.0"
pydantic-settings = "^2.1.0"
inject = "^5.2.0"
pycryptodome = "^3.20.0"
pydantic = "^2.9.2"
redis = "^5.0.8"
cryptography = "^43.0.1"
cffi = "^1.17.1"
pykcs11 = "^1.5.16"
filelock = "^3.16.1"
asn1crypto = "^1.5.1"
validators = "^0.34.0"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"
pytest-mock = "^3.14.0"
httpx = "^0.26.0"
ruff = "^0.1.13"
safety = "^2.3.5"
codespell = "^2.2.6"
types-requests = "^2.32.0.20240914"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
cache-dir = "~/.cache/ruff"
include = [
    "pyproject.toml",
    "app/*.py",
    "tests/*.py",
]

[tool.mypy]
files = "app,tests"
python_version = "3.11"
strict = true
cache_dir = "~/.cache/mypy"
ignore_missing_imports = true

[tool.pytest.ini_options]
cache_dir = "~/.cache/pytest"
testpaths = [
    "tests",
]
